import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

export type GeoCitationReportStatus = "ready" | "empty" | "invalid";

export interface GeoCitationReportData {
  site: { name: string; domain: string };
  updatedAt: string | null;
  latest: Record<string, unknown> | null;
  history: Record<string, unknown>[];
}

export interface GeoCitationReportResult {
  status: GeoCitationReportStatus;
  message?: string;
  data: GeoCitationReportData;
}

const DEFAULT_REPORT_PATH = ".local/geo-seo-citations.json";
const REQUIRED_SCHEMA_VERSION = 2;

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function isWeeklySummary(value: unknown): value is Record<string, unknown> {
  return isRecord(value) &&
    typeof value.week === "string" &&
    typeof value.responses === "number" &&
    typeof value.expectedResponses === "number" &&
    Array.isArray(value.byProvider) &&
    Array.isArray(value.byQuery) &&
    Array.isArray(value.pages) &&
    Array.isArray(value.topCitedPages);
}

function emptyData(): GeoCitationReportData {
  return {
    site: { name: "Дебрянск Авто", domain: "debryansk-auto.ru" },
    updatedAt: null,
    latest: null,
    history: [],
  };
}

function reportData(value: Record<string, unknown>): GeoCitationReportData {
  const site = isRecord(value.site) ? value.site : {};
  const weekly = Array.isArray(value.weekly) && value.weekly.every(isWeeklySummary)
    ? value.weekly
    : [];
  const history = weekly.slice(-12);

  return {
    site: {
      name: typeof site.name === "string" ? site.name : "Дебрянск Авто",
      domain: typeof site.domain === "string" ? site.domain : "debryansk-auto.ru",
    },
    updatedAt: typeof value.updatedAt === "string" ? value.updatedAt : null,
    latest: history.length ? history[history.length - 1] : null,
    history,
  };
}

/**
 * Reads the weekly GEO report generated by `geo:citations:weekly`.
 * The admin endpoint intentionally returns a non-error empty/invalid state so
 * that an absent or malformed report cannot look like a zero-citation result.
 */
export async function readGeoCitationReport(): Promise<GeoCitationReportResult> {
  const configuredPath = process.env.GEO_CITATION_REPORT || DEFAULT_REPORT_PATH;
  const reportPath = resolve(configuredPath);
  let raw: string;

  try {
    raw = await readFile(reportPath, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return {
        status: "empty",
        message: "Недельный GEO-отчёт ещё не создан.",
        data: emptyData(),
      };
    }
    return {
      status: "invalid",
      message: "Не удалось прочитать сохранённый GEO-отчёт.",
      data: emptyData(),
    };
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return {
      status: "invalid",
      message: "Сохранённый GEO-отчёт содержит некорректный JSON.",
      data: emptyData(),
    };
  }

  if (
    !isRecord(parsed) ||
    Number(parsed.schemaVersion) < REQUIRED_SCHEMA_VERSION ||
    !Array.isArray(parsed.weekly) ||
    !parsed.weekly.every(isWeeklySummary)
  ) {
    return {
      status: "invalid",
      message: "Формат GEO-отчёта не поддерживается. Запустите новый недельный замер.",
      data: emptyData(),
    };
  }

  const data = reportData(parsed);
  if (!data.latest) {
    return {
      status: "empty",
      message: "В GEO-отчёте пока нет недельных результатов.",
      data,
    };
  }

  return { status: "ready", data };
}