// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/debryansk-dynamic/Dynamic.tsx": () => import("../components/mockups/debryansk-dynamic/Dynamic.tsx"),
  "./components/mockups/brand-cards/Current.tsx": () => import("../components/mockups/brand-cards/Current.tsx"),
  "./components/mockups/brand-cards/Glassmorphic.tsx": () => import("../components/mockups/brand-cards/Glassmorphic.tsx"),
  "./components/mockups/brand-cards/Hover3D.tsx": () => import("../components/mockups/brand-cards/Hover3D.tsx"),
  "./components/mockups/brand-cards/Minimalist.tsx": () => import("../components/mockups/brand-cards/Minimalist.tsx"),
  "./components/mockups/debryansk-luxury/Luxury.tsx": () => import("../components/mockups/debryansk-luxury/Luxury.tsx"),
  "./components/mockups/email-templates/EmailBase.tsx": () => import("../components/mockups/email-templates/EmailBase.tsx"),
  "./components/mockups/email-templates/EmailCallback.tsx": () => import("../components/mockups/email-templates/EmailCallback.tsx"),
  "./components/mockups/email-templates/EmailCredit.tsx": () => import("../components/mockups/email-templates/EmailCredit.tsx"),
  "./components/mockups/email-templates/EmailFeedback.tsx": () => import("../components/mockups/email-templates/EmailFeedback.tsx"),
  "./components/mockups/email-templates/EmailOpenResume.tsx": () => import("../components/mockups/email-templates/EmailOpenResume.tsx"),
  "./components/mockups/email-templates/EmailTestDrive.tsx": () => import("../components/mockups/email-templates/EmailTestDrive.tsx"),
  "./components/mockups/email-templates/EmailTradeIn.tsx": () => import("../components/mockups/email-templates/EmailTradeIn.tsx"),
  "./components/mockups/email-templates/EmailVacancy.tsx": () => import("../components/mockups/email-templates/EmailVacancy.tsx"),
  "./components/mockups/hero-banner/HeroBanner.tsx": () => import("../components/mockups/hero-banner/HeroBanner.tsx"),
  "./components/mockups/icons/IconSet.tsx": () => import("../components/mockups/icons/IconSet.tsx"),
  "./components/mockups/modals/CreditModal.tsx": () => import("../components/mockups/modals/CreditModal.tsx"),
  "./components/mockups/modals/TestDriveModal.tsx": () => import("../components/mockups/modals/TestDriveModal.tsx"),
  "./components/mockups/modals/TradeInModal.tsx": () => import("../components/mockups/modals/TradeInModal.tsx")
};
