// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/brand-cards/Current.tsx": () => import("../components/mockups/brand-cards/Current.tsx"),
  "./components/mockups/brand-cards/Glassmorphic.tsx": () => import("../components/mockups/brand-cards/Glassmorphic.tsx"),
  "./components/mockups/brand-cards/Hover3D.tsx": () => import("../components/mockups/brand-cards/Hover3D.tsx"),
  "./components/mockups/brand-cards/Minimalist.tsx": () => import("../components/mockups/brand-cards/Minimalist.tsx"),
  "./components/mockups/debryansk-dynamic/Dynamic.tsx": () => import("../components/mockups/debryansk-dynamic/Dynamic.tsx"),
  "./components/mockups/debryansk-luxury/Luxury.tsx": () => import("../components/mockups/debryansk-luxury/Luxury.tsx")
};
